import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Build mode from argv[2]:
//   (none)       → watch, unminified + inline sourcemap  (`npm run dev`)
//   "dev"        → one-shot, unminified + inline sourcemap (`npm run build:dev`)
//   "production" → one-shot, minified, no sourcemap        (`npm run build`)
const mode = process.argv[2];
const prod = mode === "production";
const oneShot = prod || mode === "dev";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (oneShot) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
