// ─────────────────────────────────────────────
//  gen-vault — synthetic vault generator for on-device (Layer-3) perf tests
// ─────────────────────────────────────────────
//
//  The `npm run bench` harness runs in Node over in-memory fakes — it can NOT run
//  inside Obsidian's mobile WebView, and it never touches a real filesystem. To get
//  Layer-3 numbers (docs/mobile-perf-baseline-spec.md §4) — real device CPU AND real
//  Capacitor fs latency — the *device* has to perform the scenario against a real
//  vault. Nobody hand-creates 2000 notes on a phone, so this generates a throwaway
//  vault of F files of ~B bytes each (the same deterministic content the harness
//  uses, so the counts line up), which you then push to the phone and open.
//
//  Usage:
//    node bench/gen-vault.mjs --profile m [--out ./perf-vault-m]
//    node bench/gen-vault.mjs --files 2000 --bytes 6144 --out ./perf-vault-m
//    npm run gen:vault -- --profile s
//
//  Then (see the printed hints): push the notes to the device, deploy the plugin
//  into the same vault (scripts/deploy-android.sh), enable Diagnostics → Performance
//  logging, open the vault, and read `.opsblobs/perf-log.txt`.

import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const PROFILES = {
  xs: { F: 50, B: 2048 },
  s: { F: 500, B: 4096 },
  m: { F: 2000, B: 6144 },
  l: { F: 10000, B: 8192 },
  xl: { F: 20000, B: 8192 },
};

// ─── args ────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
function opt(name) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
}
if (args.includes('-h') || args.includes('--help')) {
  console.log(`gen-vault — synthetic vault for on-device perf tests

  --profile <xs|s|m|l|xl>   preset F/B (see docs/mobile-perf-baseline-spec.md §2)
  --files <N>               number of notes (overrides profile)
  --bytes <N>               ~bytes per note (overrides profile)
  --out <dir>               output dir (default ./perf-vault-<profile>)
  --clean                   remove the out dir first`);
  process.exit(0);
}

const profileKey = (opt('profile') ?? 'm').toLowerCase();
const preset = PROFILES[profileKey] ?? PROFILES.m;
const F = Number(opt('files') ?? preset.F);
const B = Number(opt('bytes') ?? preset.B);
const out = opt('out') ?? `./perf-vault-${profileKey}`;
if (!Number.isFinite(F) || F <= 0) { console.error('error: --files must be a positive number'); process.exit(2); }

// ─── deterministic content (mirrors bench/harness.ts makeText) ─────────────────
function makeText(bytes, key) {
  const lines = [];
  let size = 0, n = 0;
  while (size < bytes) {
    const line = `${key}:${n}:the quick brown fox jumps over lazy dog ${(n * 2654435761) % 1_000_000}`;
    lines.push(line);
    size += line.length + 1;
    n++;
  }
  return lines.join('\n') + '\n';
}

// ─── generate ──────────────────────────────────────────────────────────────────
if (args.includes('--clean')) rmSync(out, { recursive: true, force: true });
const notesDir = join(out, 'notes');
mkdirSync(notesDir, { recursive: true });

let totalBytes = 0;
for (let i = 0; i < F; i++) {
  const text = makeText(B, `f${i}`);
  totalBytes += text.length;
  writeFileSync(join(notesDir, `note-${i}.md`), text);
}

writeFileSync(join(out, 'PERF-TEST-VAULT.md'),
  `# Throwaway perf-test vault\n\n` +
  `Generated by \`bench/gen-vault.mjs\` for on-device (Layer-3) perf measurement — ` +
  `profile **${profileKey.toUpperCase()}** (F=${F}, ~B=${B}). Safe to delete.\n\n` +
  `Do NOT open this in a vault holding real notes: opening it triggers the ` +
  `first-enable capture (B3) over all ${F} files.\n`);

const mb = (totalBytes / 1e6).toFixed(1);
console.log(`✓ generated ${F} notes (~${mb} MB) → ${out}/notes/`);
console.log(`  profile ${profileKey.toUpperCase()}  F=${F}  ~B=${B}\n`);
console.log(`Next — run the scenario ON THE DEVICE (real fs + real CPU):`);
console.log(`  1. push the notes:`);
console.log(`       adb push "${out}/." "/sdcard/Documents/PerfVault"`);
console.log(`  2. deploy the plugin into that vault (unminified for readable traces):`);
console.log(`       scripts/deploy-android.sh --build-dev "/sdcard/Documents/PerfVault"`);
console.log(`  3. on the phone: open the "PerfVault" vault, enable the plugin, then`);
console.log(`     Settings → Diagnostics → Performance logging = on.`);
console.log(`  4. trigger scenarios and read \`.opsblobs/perf-log.txt\`:`);
console.log(`       • B3 (first-enable capture): happens automatically on first open`);
console.log(`         → look for the \`startup captureOfflineChanges\` line.`);
console.log(`       • B1 (steady-state round): edit one note, tap Sync now`);
console.log(`         → the \`round buildLocalState\` / \`round total\` lines.`);
console.log(`     (B1/B4 need the server configured; B3/B5 do not.)`);
